FROM ubuntu:26.04

ENV TZ="Asia/Tokyo"
ENV DEBIAN_FRONTEND=noninteractive

RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo "${TZ}" > /etc/timezone

# OpenWRTビルドに必要なパッケージ
# 公式: https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem
RUN set -eux \
    && apt-get update \
    && apt-get full-upgrade -y \
    && apt-get install -y --no-install-recommends \
    build-essential clang flex bison g++ gawk \
    gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
    python3-distutils-extra rsync unzip zlib1g-dev file wget \
    ca-certificates curl sudo nano vim-tiny xz-utils \
    python3 python3-pip python3-setuptools \
    swig time ccache \
    && rm -rf /var/lib/apt/lists/* \
    && echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER ubuntu
WORKDIR /home/ubuntu

CMD ["/bin/bash"]
